import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/NavBar";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children:
        React.ReactNode }>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} $
{geistMono.variable} antialiased bg-gray-50 text-gray-800`}
        >
        <Navbar />
        <main className="p-6">{children}</main>
        </body>
        </html>
    );
}
